package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net"
	"net/http"
	"time"

	"github.com/shirou/gopsutil/v4/cpu"
	"github.com/shirou/gopsutil/v4/mem"
)

//Welcome to the code of VivusAgent! I warn you, this code is probably terrible!
//This was my first EVER Go project.
//None of this code was generated by AI. The only use of AI was research, learning and debugging.

//This is a struct containing all the response data.
type ResponseData struct {
	Percent int `json:"processing"`
	Memory int `json:"memory"`
	Device string `json:"device"`
}

// I discovered this awesome technique from gosamples.dev! 
// There's a link to the article at the bottom of this file.
func getLocalIP() string {
	//First, it uses UDP to communicate with an (arbitrary) address
	connection, err := net.Dial("udp", "8.8.8.8:80")

	//Check for errors! :D
	if(err != nil) {
		log.Fatal(err)
	}
	//This one kinda confused me, but I believe it defers running the close function until the rest has finished. 
	defer connection.Close()
	//A bunch of fancy logic stuff I don't really understand in all honesty
	localAddress := connection.LocalAddr().(*net.UDPAddr)

	//Return the stringified IP address :)
	return localAddress.IP.String();
	
}


func getStatus(response http.ResponseWriter, requestBody *http.Request) {
//Check memory usage using the import :)
	ram, err := mem.VirtualMemory()
	//Check CPU usage.
	cpuPercent, err := cpu.Percent(time.Second, false)
	
	//Checks if something fails
	if err != nil {
		log.Fatal("Error occurred,", err)
	}
	//Fetch CPU info
	infos, cpuInfoErr := cpu.Info()
	//Check for errors!
	if cpuInfoErr != nil {
		log.Fatal("Error occurred,", err)
	}
	//Get the CPU model name (e.g, Apple M2) 
	cpuModel := infos[0].ModelName

	//Format the response data with a struct!
	formatted := ResponseData{
		Percent: int(cpuPercent[0]),
		Memory: int(ram.UsedPercent),
		Device: cpuModel,
	}
	//Yeet the "ok" header to the device
	response.WriteHeader(http.StatusOK)
	//Make the response into some nice JSON
	json.NewEncoder(response).Encode(formatted)
}

//Some basic code to handle when a client arrives
func handleIncoming() {
	
	http.Handle("/stats", http.HandlerFunc(getStatus)) 
	//Checks if something goes wrong with the ListenAndServe function
	log.Fatal(http.ListenAndServe(":4354", nil))
}

func main() {
	//Use our fancy function to get the IP
	ipAddress := getLocalIP()
	//Print AWESOME ASCII logo XD
	fmt.Println(` _  _  __  _  _  _  _  ____ 
/ )( \(  )/ )( \/ )( \/ ___)
\ \/ / )( \ \/ /) \/ (\___ \
 \__/ (__) \__/ \____/(____/ `)

	//Makes a nice little gap for the logo and a thank you.
	fmt.Println("\n" + "Thanks for running Vivus!" + "\n" + "____________________________")
	//Info about how to read it all.
	fmt.Println("\n", "Setup completed. Hosting at http://" + ipAddress + ":4354")
	fmt.Println("Visit http://" + ipAddress + ":4354" + "/stats", "too see the data.")
	//Run our function.
	handleIncoming();
	
}

//Online learning resources used: 
// https://www.w3schools.com/go/go_arrays.php
// https://blog.alexellis.io/golang-json-api-client/
// https://gosamples.dev/local-ip-address/

//All of these amazing websites helped me a ton while making this project!
//Thanks for reading the code! 